export const ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  UPDATE_PASSWORD: "/update-password",
  ADD_DETAILS: "/add-details",
  PROFILE: "/profile",
  REFRESH_USER: "/refreshUser",
  BUSINESSES: "/business",
  BUSINESS: (id) => `/business/${id}`,
  SUB_BUSINESSES: (id) => `/business/${id}/sub-businesses`,
  BUSINESS_NUMBER: (id) => `/getNumber/${id}`,
  PRODUCTS: "/products",
  PRODUCT: (id) => `/products/${id}`,
  PRODUCT_STATUS: (id) => `/product/${id}/status`,
  BUSINESS_PRODUCTS: (id) => `/all-products/${id}`,
  BUSINESS_PRODUCTS_ADMIN: (id) => `/all-products/${id}/admin`,
  RANDOM_PRODUCTS: "/random-products",
  BUSINESS_PRODUCTS_DISCOUNT: (id) => `/business/${id}/products`,
  BUSINESS_TYPES: (id) => `/businessTypes/${id}`,
  PRODUCTS_FILTERED: (id) => `/products/${id}/filtered`,
  UPDATE_GROCERY_BUSINESS_ID: "/update-grocery-business-id",
  DELETE_PRODUCTS: (id) => `/delete-products/${id}`,
  CART: "/cart",
  CART_ITEM: (id) => `/cart/${id}`,
  CART_PRODUCT: (id) => `/cart/product/${id}`,
  CART_UPDATE: (id) => `/cart/update/${id}`,
  CART_ITEM_COUNT: "/cart/item-count",
  CART_APPLY_VOUCHER: "/cart/apply-voucher",
  ORDER: "/order",
  ORDERS: (id) => `/orders/${id}`,
  ORDER_STATUS: (id) => `/orders/${id}/status`,
  REORDER: (id) => `/reorder/${id}`,
  DELETE_ALL_ORDERS: "/orders/delete-all",
  TOWNS: "/towns",
  TOWN: (id) => `/towns/${id}`,
  GET_TOWNS: "/get-towns",
  UPDATE_HOUSEHOLD: "/update/household",
  UPDATE_USER: (id) => `/update/${id}`,
  DELETE_USERS: "/users/cleanup",
  REVIEWS: (id) => `/reviews/${id}`,
  CREATE_REVIEW: "/reviews",
  COMPLAINTS: "/complaints",
  APPLY_VOUCHER: "/cart/apply-voucher",
  EASY_BUY: "/easy-buy",
  EASY_BUY_ITEM: (id) => `/easy-buy/${id}`,
  EASY_BUY_FILTERS: "/easy-buy/filters",
  RESOLVE_PRODUCT: "/resolve-product",
  HEADER_IMAGES: "/header-images",
  HEADER_IMAGE: (id) => `/header-images/${id}`,
  HEADER_IMAGES_REORDER: "/header-images/reorder",
  PRESCRIPTION: "/prescription",
  INTERNSHIP_APPLY: "/internship/apply",
  POS_PRODUCTS: "/pos-products",
  POS_PRODUCTS_IMPORT: "/pos-products/import",
  IMPORT_GROCERY: "/import-grocery-products",
  UPLOAD_IMAGE: "/upload/image",
  UPLOAD_IMAGES: "/upload/images",
  ADMIN_USERS: "/admin/users",
  ADMIN_USER: (id) => `/admin/users/${id}`,
  ADMIN_USERS_RECENT: "/admin/users/previous-two-days",
  ADMIN_CREATE_ADMIN: "/admin/createAdmins",
  ADMIN_VENDORS: "/admin/vendors",
  ADMIN_UPDATE_ADMIN: (id) => `/admin/admins/${id}`,
  ADMIN_BUSINESS_ORDERS: (id) => `/admin/business-orders/${id}`,
  ADMIN_GROCERY_USERS: (id) => `/admin/grocery/${id}`,
  ADMIN_BUSINESS_STATS: "/admin/business-stats",
  ADMIN_CREATE_VOUCHER: "/admin/create-voucher",
  ADMIN_GET_VOUCHERS: "/admin/get-voucher",
  ADMIN_DELETE_VOUCHER: (id) => `/admin/voucher/${id}/delete`,
  ADMIN_INTERNSHIP_APPS: "/admin/internship-applications",
  ADMIN_RIDER_APPS: "/admin/rider-applications",
  ADMIN_RIDER_APP: (id) => `/admin/rider-applications/${id}`,
  ADMIN_RIDER_APP_STATUS: (id) => `/admin/rider-applications/${id}/status`,
  ADMIN_RIDER_APP_DOCUMENT: (id) => `/admin/rider-applications/${id}/document`,
  ADMIN_RIDER_APP_MESSAGE: (id) => `/admin/rider-applications/${id}/message`,
  RESTAURANT_REVIEWS: "/restaurantAdmin/get-reviews",
  RESTAURANT_BUSINESS: "/restaurantAdmin/business",
  RESTAURANT_REPLY_REVIEW: (id) => `/restaurantAdmin/review/${id}/reply`,
  RESTAURANT_COMPLAINT_STATUS: "/restaurantAdmin/complaint-status",
  RESTAURANT_COMPLAINTS: "/restaurantAdmin/complaints",
  RESTAURANT_PRODUCTS: "/restaurantAdmin/allproducts",
  RESTAURANT_ORDERS: "/restaurantAdmin/orders",
  ORDER_ASSIGN_RIDER: (id) => `/restaurantAdmin/orders/${id}/assign-rider`,
  RESTAURANT_DISCOUNT: "/restaurantAdmin/products/discount",
  RESTAURANT_REMOVE_DISCOUNT: "/restaurantAdmin/products/removeDiscount",
  RESTAURANT_ADD_PRODUCT: "/restaurantAdmin/add-products",
  RESTAURANT_APPLY_DISCOUNT: (id) => `/restaurantAdmin/products/${id}/apply-discount`,
  RESTAURANT_TOGGLE_ACTIVE: (id) => `/restaurantAdmin/products/${id}/toggle-active`,
  RESTAURANT_RIDERS: "/restaurantAdmin/riders",
  RESTAURANT_RIDER: (id) => `/restaurantAdmin/riders/${id}`,
  RESTAURANT_RIDER_TOGGLE: (id) => `/restaurantAdmin/riders/${id}/toggle`,
};
